hook: "convert '/home/alexandre/Pictures/wallpaper_blank.png' '$W' -gravity center -compose over -composite '$W';"
      "nitrogen --head=0 --set-scaled $W;"
      "nitrogen --head=1 --set-scaled $W;"
      "betterlockscreen -u ~/.cache/pacwall/pacwall.png --blur 1"

shell: "bash"

attributes: {
    graph: "bgcolor='#1e2127'"
    package: {
        common:     "shape=point, height=0.1, fontname='FiraCode Nerd Font', fontsize=10"
        implicit:   "color='#98c379'"
        explicit:   "color='#61afef'"
        orphan:     "color='#c678dd', fontcolor='#c678dd', peripheries=2, xlabel='\\N'"
        unneeded:   ""
        outdated:   "color='#d19a66', fontcolor='#d19a66', peripheries=3, xlabel='\\N'"
        unresolved: "color='#e06c75', fontcolor='#e06c75', peripheries=4, xlabel='\\N'"
        repository: {
            core: ""
            extra: ""
            community: ""
            multilib: ""
            *: "color='#5e81ac'"
        }
    }
    dependency: {
        common:   "color='#434c5e2a'"
        hard:     ""
        optional: "arrowhead=empty, style=dashed"
    }
}
