hook: "convert '/home/alexandre/Pictures/wallpaper_blank.png' '$W' -gravity center -compose over -composite '$W';"
      "nitrogen --head=0 --set-scaled $W;"
      "nitrogen --head=1 --set-scaled $W;"
      "betterlockscreen -u ~/.cache/pacwall/pacwall.png --blur 1"

shell: "bash"

attributes: {
    graph: "bgcolor='#11111b'"
    package: {
        common:     "shape=point, height=0.1, fontname='JetBrainsMono Nerd Font', fontsize=10"
        implicit:   "color='#cba6f7'"
        explicit:   "color='#f5c2e7'"
        orphan:     "color='#89dceb', fontcolor='#89dceb', peripheries=2, xlabel='\\N'"
        unneeded:   ""
        outdated:   "color='#f9e2af', fontcolor='#f9e2af', peripheries=3, xlabel='\\N'"
        unresolved: "color='#f38ba8', fontcolor='#f38ba8', peripheries=4, xlabel='\\N'"
        repository: {
            core: ""
            extra: ""
            community: ""
            multilib: ""
            *: "color='#5e81ac'"
        }
    }
    dependency: {
        common:   "color='#4145592a2a'"
        hard:     ""
        optional: "arrowhead=empty, style=dashed"
    }
}
