[colors]

rosewater = #F5E0DC
flamingo = #F2CDCD
pink = #F5C2E7
mauve = #CBA6F7
red = #F38BA8
maroon = #EBA0AC
peach = #FAB387
yellow = #F9E2AF
green = #A6E3A1
teal = #94E2D5
sky = #89DCEB
blue = #90C1FB
sapphire = #74C7EC
lavender = #B4BEFE
foreground = #C6D0F5
overlay2 = #9399b2
overlay1 = #969DBC
overlay0 = #7E84A0
surface2 = #666A83
surface1 = #4E5167
surface0 = #36374A
background = #1E1E2E
base1 = #12121C
base0 = #07070A

[bar/main]
monitor = ${env:monitor}
width = 100%:-10
offset-x = 5
offset-y = 10

height = 30
radius = 15.0

override-redirect = true
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 1
padding-right = 1
module-margin-left = 1
module-margin-right = 1

font-0 = JetBrainsMono Nerd Font:pixelsize=12:antialias=true;2.5
font-1 = JetBrainsMono nerd font:style=regular:pixelsize=16:antialias=true;3
font-2 = JetBrainsMono nerd font:style=regular:pixelsize=18:antialias=true;3
font-3 = JetBrainsMono nerd font:style=regular:pixelsize=19:antialias=true;3

modules-left = ewmh 
modules-center = xwindow
modules-right = arch-updates vpn-wireguard-wg cpu memory xkeyboard audio popup-calendar powermenu

cursor-click = pointer
cursor-scroll = ns-resize

[bar/mainbar0]
inherit = bar/main
tray-position = right
tray-padding = 0
tray-maxsize = 16
tray-detached = false

[bar/mainbar1]
inherit = bar/main

[module/xwindow]
type = internal/xwindow
format=   <label>
format-foreground=${colors.blue}
label = %title:0:20:...%

label-empty = alexandre@orth
label-empty-foreground=${colors.blue}


[module/filesystem]
type = internal/fs
interval = 25111
mount-0 = /
label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground}


[module/ewmh]
type = internal/xworkspaces
pin-workspaces = false
enable-click = true
enable-scroll = false

icon-default = "  "
icon-0 = "home;%{T2}  %{T-}"
icon-1 = "code;%{T2}  %{T-}"
icon-2 = "web;%{T2}  %{T-}"
icon-3 = "mail;%{T2}  %{T-}"
icon-4 = "socials;%{T2} 切 %{T-}"
icon-5 = "files;%{T2}  %{T-}"
icon-6 = "music;%{T2}  %{T-}"
icon-7 = "live;%{T2}  %{T-}"
icon-8 = "txt;%{T2}  %{T-}"
icon-9 = "9;9" 


label-active =  
label-active-foreground = ${colors.mauve}
label-active-background = ${colors.background}
label-active-padding = 1
label-active-font = 2

label-empty =   
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1
label-empty-font = 2

label-occupied =   
label-occupied-foreground = ${colors.mauve}
label-occupied-padding = 1
label-occupied-font = 2

label-urgent =   
label-urgent-foreground = ${colors.blue}
label-urgent-padding = 1
label-urgent-font = 2

[module/lan]
type = internal/network
interface = enp42s0
interval = 3.0

format-connected = <label-connected>
label-connected =  
label-connected-foreground = ${colors.magenta}

format-disconnected = <label-disconnected>
label-disconnected = 
label-disconnected-foreground = ${colors.magenta}

[module/date]
type = internal/date
interval = 1

date = "%b %d, %Y"
format-foreground = ${colors.yellow}
format-underline = ${colors.yellow}
label =  %date%

[module/time]
type = internal/date
interval = 1

time = "%l:%M %p"

format-foreground = ${colors.green}
format-underline = ${colors.green}
label =  %time%


[module/audio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume-foreground = ${colors.yellow}
ramp-volume-foreground = ${colors.yellow}
label-volume = %percentage%% 

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

label-muted = ﱝ 0%
label-muted-foreground = ${colors.overlay2}

click-right= pavucontrol

[module/powermenu]
type = custom/text
content-padding = 2
content = 
content-foreground = ${colors.background}
content-background = ${colors.red}
click-left = bash ~/bin/powermenu.sh

[module/xkeyboard]
type = internal/xkeyboard

; List of indicators to ignore
blacklist-0 = scroll lock

; Available tags:
;   <label-layout> (default)
;   <label-indicator> (default)
format = <label-layout> <label-indicator>
format-spacing = 0

; Available tokens:
;   %layout%
;   %name%
;   %number%
;   %icon%
;   %variant% (unreleased)
; Default: %layout%
label-layout = %icon%  %layout%
label-layout-foreground = #a6e3a1

; layout-icon-[0-9]+ = layout;icon
; Assign each layout an icon that will be available as %icon% token for the
; <label-layout> tag. The part before ';' will try to match %layout% value.
layout-icon-default =  

; Replaces label-indicator-* if for specific indicators
; Available tokens:
;   %name%
;   %icon%
label-indicator-on-capslock = %{F#a6e3a1}בּ%{F-} 
label-indicator-off-capslock = " "  
label-indicator-on-numlock = ""

[module/memory]
type = internal/memory

; Seconds to sleep between updates
; Default: 1
interval = 3

; Default: 90
; New in version 3.6.0
warn-percentage = 80

label = %{F#94e2d5} %percentage_used%%%{F-}
label_warn = %{F#f38ba8} %percentage_used%%%{F-}

[module/cpu]
type = internal/cpu

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Default: 80
; New in version 3.6.0
warn-percentage = 80

label = %{F#94e2d5} %percentage%%%{F-}
label_warn = %{F#f38ba8} %percentage%%%{F-}

[module/arch-updates]
type = custom/script
exec = $HOME/bin/check-arch-updates.sh
interval = 1000
label = ﮮ %output%
format-foreground = ${colors.lavender}
format-background = ${colors.background}
format-prefix-foreground = ${color.lavender}
click-left = alacritty -e fish ~/bin/update.sh
click-right = alacritty -e fish ~/bin/update.sh

[module/popup-calendar]
type = custom/script
exec = $HOME/bin/popup-calendar.sh
interval = 5
click-left = $HOME/bin/popup-calendar.sh --popup &
label = %{F#fab387} %output%%{F-}

[module/vpn-wireguard-wg]
type = custom/script
exec = $HOME/bin/vpn-wireguard-wg.sh
interval = 5
click-left = $HOME/bin/vpn-wireguard-wg.sh --toggle &
label = %output%

[module/custom_battery]
type = custom/script
exec = $HOME/bin/battery.sh
interval = 10
label = %{F#89dceb}%output%%{F-}

[module/battery]
;https://github.com/jaagr/polybar/wiki/Module:-battery
type = internal/battery
battery = BAT1
adapter = AC
full-at = 96

format-charging = <animation-charging>  <label-charging>
label-charging = %{F#89dceb} %percentage%%%{F-}

format-discharging = <ramp-capacity>  <label-discharging>
label-discharging = %{F#89dceb} %percentage%%%{F-}

format-full-prefix = "  "
format-full-prefix-foreground = ${colors.green}
;format-full-underline = #a3c725
format-full-foreground = ${colors.sky}
format-full-background = ${colors.background}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.sky}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.sky}
animation-charging-framerate = 750

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency =true

[global/wm]
margin-bottom = 10
margin-top = 5
