theme = "custom"

[editor]
line-number = "relative"
color-modes = true
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
